#!/bin/bash
# WaxLab — Netlify build script
# Only job: inject Supabase credentials from Netlify env vars into config.js

echo "Writing config.js..."

cat > config.js << EOF
// Auto-generated by build.sh at deploy time — do not edit or commit.
window.WAXLAB_CONFIG = {
  SUPABASE_URL:      "${SUPABASE_URL:-}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY:-}",
  GOOGLE_CLIENT_ID:  "${GOOGLE_CLIENT_ID:-}"
};
EOF

echo "Done. SUPABASE_URL is ${SUPABASE_URL:+set}${SUPABASE_URL:-NOT SET}."
