#!/bin/bash
# WaxLab — Netlify build script
# Injects credentials from Netlify env vars into config.js

echo "Writing config.js..."

cat > config.js << CONFIGEOF
// Auto-generated by build.sh at deploy time — do not edit or commit.
window.WAXLAB_CONFIG = {
  SUPABASE_URL:      "${SUPABASE_URL:-}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY:-}",
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY:-}",
  GOOGLE_CLIENT_ID:  "${GOOGLE_CLIENT_ID:-}"
};
CONFIGEOF

echo "Done."
echo "  SUPABASE_URL:      ${SUPABASE_URL:+set}${SUPABASE_URL:-NOT SET}"
echo "  SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:+set}${SUPABASE_ANON_KEY:-NOT SET}"
echo "  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:+set}${ANTHROPIC_API_KEY:-NOT SET}"
