// config.js — LOCAL DEVELOPMENT placeholder
//
// On Netlify this is auto-generated by build.sh from environment variables.
// For local development fill in Supabase credentials here.
// DO NOT commit real credentials to GitHub.
//
// ANTHROPIC_API_KEY is NOT here — it lives server-side in netlify/functions/claude-proxy.js

window.WAXLAB_CONFIG = {
  SUPABASE_URL:      "",   // e.g. "https://abcxyz.supabase.co"
  SUPABASE_ANON_KEY: "",   // your project's public anon key
  GOOGLE_CLIENT_ID:  ""    // optional
};
