// config.js — LOCAL DEVELOPMENT placeholder
//
// This file is gitignored on production (Netlify generates it from env vars).
// For local development, fill in your credentials here.
//
// DO NOT commit real credentials to GitHub.
// On Netlify, this file is auto-generated by build.sh from environment variables.

window.WAXLAB_CONFIG = {
  SUPABASE_URL:      "",   // e.g. "https://abcxyz.supabase.co"
  SUPABASE_ANON_KEY: "",   // your project's public anon key
  ANTHROPIC_API_KEY: "",   // your Anthropic API key (sk-ant-...)
  GOOGLE_CLIENT_ID:  ""    // optional, only for Google Sheets export
};
